### ISSUE TITLE
运行速度问题。

### ISSUE THREAD

**Issue by Jinyong-Huang** [USTC-Keyanjie/Pseudo-LiDAR-End-to-End#1]
请问处理单帧图像大概花费时间是多少呀。

**Comment by USTC-Keyanjie** [comment]
2080Ti的显卡也需要2~3秒一帧

**Comment by Jinyong-Huang** [comment]
多谢回复，我想请教一下，如果要将pseudo lidar的方案做成实时的，请问可以从哪些方面改进。

**Comment by USTC-Keyanjie** [comment]
我个人认为不太可能，主要是双目匹配部分太耗时。如果使用深度补全的方法，将图片与稀疏激光雷达（4线~12线）融合，下游再接3D目标检测网络，还是有可能的。

**Comment by Jinyong-Huang** [comment]
但我看到你用的双目匹配方法GA-net，论文上提到 GA-Net-1  15∼20 fps for 300×1000 images on a TESLA P40 GPU；感觉也不会慢吧。

**Comment by USTC-Keyanjie** [comment]
GA-Net 的开源代码只有GA-Net 11和GA-Net deep（应该是GA-Net 15），我为了获得更好的深度图，使用的是GA-Net deep

**Comment by Jinyong-Huang** [comment]
我看了一下深度补全的论文，RGB图像加稀疏点云做深度补全，速度蛮快的，但是为什么之前没有人尝试这种方法来估计深度再做3D检测，有局限性嘛。

**Comment by USTC-Keyanjie** [comment]
有什么局限性我也不清楚，毕竟没有尝试过没有发言权。我个人觉得这是一条可以走的通的路，你可以研究下去。

**Comment by Jinyong-Huang** [comment]
好的，多谢指点。

**Comment by Jinyong-Huang** [comment]
你说的稀疏激光雷达是按照不同的线来分的？比如（4线~12线）。但是我看论文，sparse lidar不是按照线来划分呀，好像都可以这么叫。

**Comment by USTC-Keyanjie** [comment]
激光雷达分为很多种，最稠密的有128线，稀疏的有4线，如果这篇文章不是针对特定线数的雷达进行优化，他会统称为spare lidar，具体的你搜搜相关资料。

**Comment by Jinyong-Huang** [comment]
这样子的话，现有论文基于lidar来做深度补全应该指得是32线或者64线，没有看到4-12线lidar和图像来做深度补全的。估计是效果很差。

---原始邮件---
发件人: "Alan"<notifications@github.com&gt;
发送时间: 2020年4月19日(周日) 下午5:47
收件人: "USTC-Keyanjie/Pseudo-LiDAR-End-to-End"<Pseudo-LiDAR-End-to-End@noreply.github.com&gt;;
抄送: "Jinyong-Huang"<543401923@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [USTC-Keyanjie/Pseudo-LiDAR-End-to-End] 运行速度问题。 (#1)




 
激光雷达分为很多种，最稠密的有128线，稀疏的有4线，如果这篇文章不是针对特定线数的雷达进行优化，他会统称为spare lidar，具体的你搜搜相关资料。

**Comment by USTC-Keyanjie** [comment]
据我所知，我知道有公司在这么做，而且效果还行。另外建议阅读一下Pseudo-Lidar++这篇论文，他使用4线激光雷达对深度图进行矫正。

**Comment by Jinyong-Huang** [comment]
我看了这篇论文，还是用的双目来求深度，4线lidar可以提高深度估计的准确性吧，但双目深度估计运行速度还是很慢。我们公司是打算尽可能降低成本去做的，如果速度上去了，这种方法应该可行。



---原始邮件---
发件人: "Alan"<notifications@github.com&gt;
发送时间: 2020年4月19日(周日) 下午5:58
收件人: "USTC-Keyanjie/Pseudo-LiDAR-End-to-End"<Pseudo-LiDAR-End-to-End@noreply.github.com&gt;;
抄送: "Jinyong-Huang"<543401923@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [USTC-Keyanjie/Pseudo-LiDAR-End-to-End] 运行速度问题。 (#1)




 
据我所知，我知道有公司在这么做，而且效果还行。另外建议阅读一下Pseudo-Lidar++这篇论文，他使用4线激光雷达对深度图进行矫正。

**Comment by Jinyong-Huang** [comment]
能否透露一下具体是哪些公司采用低成本的激光雷达来辅助深度估计的？



---原始邮件---
发件人: "Alan"<notifications@github.com&gt;
发送时间: 2020年4月19日(周日) 下午5:58
收件人: "USTC-Keyanjie/Pseudo-LiDAR-End-to-End"<Pseudo-LiDAR-End-to-End@noreply.github.com&gt;;
抄送: "Jinyong-Huang"<543401923@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [USTC-Keyanjie/Pseudo-LiDAR-End-to-End] 运行速度问题。 (#1)




 
据我所知，我知道有公司在这么做，而且效果还行。另外建议阅读一下Pseudo-Lidar++这篇论文，他使用4线激光雷达对深度图进行矫正。

**Comment by USTC-Keyanjie** [comment]
那你的情况只有找找看有没有较快的双目匹配网络，图像+稀疏激光雷达进行补全的方法我知道有公司在做，抱歉哪家公司不能透露

**Comment by Jinyong-Huang** [comment]
好的，多谢指点。
